### ISSUE TITLE
Issues of ACEScc and ACEScct Color Checker images

### ISSUE THREAD

**Issue by DevTGHa** [colour-science/colour-nuke#4]
The ColorChecker image in `ACEScc` and `ACEScct` seems to be same with `ACEScg`.
My understanding is that as `ACEScg` is in linear space, whereas `ACEScc` and `ACEScct` are in gamma space, they are expected to have different pixel value.
Would it be possible to get a confirmation on this?

The images I'm referring to are:
- `colour_nuke/resources/images/ColorChecker2014/ACEScc_ColorChecker2014.exr`
- `colour_nuke/resources/images/ColorChecker2014/ACEScct_ColorChecker2014.exr`
- `colour_nuke/resources/images/ColorChecker2014/ACEScg_ColorChecker2014.exr`
- `colour_nuke/resources/images/ColorChecker2005/ACEScc_ColorChecker2005.exr`
- `colour_nuke/resources/images/ColorChecker2005/ACEScct_ColorChecker2005.exr`
- `colour_nuke/resources/images/ColorChecker2005/ACEScg_ColorChecker2005.exr`

**Comment by thomasmansencal** [comment]
Hello,

This is a great question,the colour checkers that we ship here are linearly encoded, i.e., without a transfer function, because they are stored in EXR files. As such, some might be exactly the same, e.g., ACEScg and ACEScc, because they use the same primaries.

Cheers,

Thomas

**Comment by DevTGHa** [comment]
Hello Thomas,

That makes a lot of sense. Thanks for your explanation.

Kind regards,
Taegyun
